/nv/item_files/wcdma/rrc/wcdma_rrc_wtol_cm_support
/nv/item_files/wcdma/rrc/wcdma_ppac_support
/nv/item_files/wcdma/rrc/wcdma_rrc_disable_cpc_fdpch
/nv/item_files/wcdma/rrc/wcdma_rrc_wtol_ps_ho_support
/nv/item_files/wcdma/rrc/wcdma_rrc_band_priority_config
/nv/item_files/wcdma/rrc/wcdma_rrc_wtol_tdd_ps_ho_support
/nv/item_files/wcdma/rrc/wcdma_rrc_dormancy_support 
